version: '3'
services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: always

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: always
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
      
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    restart: always
    environment:
      - REDIS_HOST=redis
      - REFRESH_RATE=1.0
    depends_on:
      - redis
    deploy:
      replicas: 2

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      
volumes:
  redis_data:
  portainer_data: